language: node_js
node_js:
  - 'stable'
  - '0.12'
  - '0.10'
before_install:
  - 'npm i -g npm@latest'
after_success:
  - '[ -z "$COVERALLS_REPO_TOKEN" ] && tap --coverage-report=text-lcov | ./node_modules/.bin/coveralls'
cache:
  directories:
    - node_modules
