language: node_js
os:
  - windows
  - linux
node_js:
  - 11
  - 10
  - 8
  - 6
env:
  - FRESH_DEPS=false
  - FRESH_DEPS=true
matrix:
  exclude:
    - node_js: 11
      env: FRESH_DEPS=true
    - node_js: 8
      env: FRESH_DEPS=true
    - node_js: 6
      env: FRESH_DEPS=true
    - node_js: 10
      env: FRESH_DEPS=true # Assume any bugs that occur with fresh dependencies are not platform specific.
      os: windows
    - node_js: 6
      os: windows # npm install --global currently fails on Windows. Skip the tests entirely instead.
cache: npm
before_install: if [[ "$(npm -v)" != "6.6.0" ]] && [[ "${TRAVIS_OS_NAME}" != "windows" ]]; then npm install --global npm@6.6.0; fi
install: npm ci
before_script: |
  if [[ ${FRESH_DEPS} == "true" ]]; then
    npm install --no-shrinkwrap --prefer-online
  elif [[ "${TRAVIS_OS_NAME}" != "windows" ]]; then
    checksum=$(md5sum package-lock.json)
    npm install --package-lock-only
    if ! echo ${checksum} | md5sum --quiet -c -; then
      echo "package-lock.json was modified unexpectedly. Please rebuild it using npm@$(npm -v) and commit the changes."
      exit 1
    fi
  fi

  if [[ "${TRAVIS_OS_NAME}" == "windows" ]]; then
    git config core.symlinks true
    git reset --hard
  fi
after_success: npx codecov --file=./coverage/lcov.info
