language: node_js
node_js:
  - 9
  - 8
  - 6
  - 4
env:
  - FRESH_DEPS=false
  - FRESH_DEPS=true
matrix:
  exclude:
    - node_js: 9
      env: FRESH_DEPS=true
    - node_js: 6
      env: FRESH_DEPS=true
    - node_js: 4
      env: FRESH_DEPS=true
cache:
  directories:
    - $HOME/.npm
before_install:
  - npm install --global npm@5.6.0
  - npm --version
install:
  - if [[ ${FRESH_DEPS} == "true" ]]; then npm install --no-shrinkwrap --prefer-online; else npm install --prefer-offline; fi
after_success: npx codecov --file=./coverage/lcov.info
