environment:
  matrix:
    - nodejs_version: '0.10'
    - nodejs_version: '5'
    - nodejs_version: '4'
    - nodejs_version: '0.12'
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - set AVA_APPVEYOR=true
  - npm -g install npm@latest || (timeout 30 && npm -g install npm@latest)
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install || (timeout 30 && npm install)
matrix:
  fast_finish: true
build: off
version: '{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - node --version
  - npm --version
  - npm run test-win || (timeout 30 && npm run test-win)
