build: off
cache:
  - '%APPDATA%\npm-cache'
clone_depth: 1
skip_branch_with_pr: true
skip_commits:
  files:
    - '**/*.md'
configuration:
  - FreshDeps
  - LockedDeps
environment:
  matrix:
    - nodejs_version: 10
    - nodejs_version: 9
    - nodejs_version: 8
    - nodejs_version: 6
matrix:
  fast_finish: true
  exclude:
    - configuration: FreshDeps
      nodejs_version: 9
    - configuration: FreshDeps
      nodejs_version: 8
    - configuration: FreshDeps
      nodejs_version: 6
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --global npm@6.1.0
  - npm --version
  - git config core.symlinks true
  - git reset --hard
  - if %configuration% == FreshDeps (npm install --no-shrinkwrap --prefer-online)
  - if %configuration% == LockedDeps (npm ci)
test_script:
  - npm run test-win
